/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void CheckIfTwoPlusTwoIsFour() {
        int expectedResult = 4;
        int actualResult = 2 + 2;
        Assert.assertEquals(expectedResult, actualResult);
    }

    @Test
    public void CheckIfTwoPlusTwoIsFive() {
        int expectedResult = 5;
        int actualResult = 2 + 2;
        Assert.assertEquals(expectedResult, actualResult);
    }
}
